/* =====================================================
   CasaShoes — Image Build Script
   Converts every JPG/PNG in /images (except /images/icons)
   to WebP + AVIF, and writes a dimensions manifest so the
   front-end can render width/height without extra network
   requests (prevents CLS).

   Usage: node build-images.js
   ===================================================== */

const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const IMAGES_DIR = path.join(__dirname, 'images');
const MANIFEST_PATH = path.join(__dirname, 'js', 'image-manifest.js');

const VALID_EXT = /\.(jpe?g|png)$/i;

async function processImage(fileName) {
  const fullPath = path.join(IMAGES_DIR, fileName);
  const baseName = fileName.replace(VALID_EXT, '');
  const webpPath = path.join(IMAGES_DIR, `${baseName}.webp`);
  const avifPath = path.join(IMAGES_DIR, `${baseName}.avif`);

  const img = sharp(fullPath);
  const meta = await img.metadata();

  // WebP — quality 84 keeps product detail crisp while cutting size ~65-80%
  await sharp(fullPath)
    .rotate() // respect EXIF orientation before encoding
    .webp({ quality: 84, effort: 5 })
    .toFile(webpPath);

  // AVIF — cqLevel ~30 is visually lossless for product photography
  await sharp(fullPath)
    .rotate()
    .avif({ quality: 55, effort: 4 }) // sharp's avif "quality" ~ maps to good visual match at 55-60
    .toFile(avifPath);

  return {
    file: fileName,
    width: meta.width,
    height: meta.height
  };
}

async function run() {
  const files = fs.readdirSync(IMAGES_DIR).filter(f => VALID_EXT.test(f));
  console.log(`Found ${files.length} images to convert...`);

  const manifest = {};
  let done = 0;

  for (const file of files) {
    try {
      const result = await processImage(file);
      manifest[`images/${file}`] = { width: result.width, height: result.height };
      done++;
      process.stdout.write(`\r  Converted ${done}/${files.length}`);
    } catch (err) {
      console.error(`\nFailed on ${file}:`, err.message);
    }
  }

  fs.writeFileSync(
    MANIFEST_PATH,
    `/* Auto-generated by build-images.js — do not edit by hand.\n   Maps original image path -> { width, height } so the front-end\n   can render correct width/height attributes without extra requests. */\nwindow.IMAGE_MANIFEST = ${JSON.stringify(manifest, null, 2)};\n`
  );
  console.log(`\nDone. Manifest written to js/image-manifest.js`);

  // Report size savings
  let originalTotal = 0;
  let webpTotal = 0;
  let avifTotal = 0;
  for (const file of files) {
    const base = file.replace(VALID_EXT, '');
    originalTotal += fs.statSync(path.join(IMAGES_DIR, file)).size;
    webpTotal += fs.statSync(path.join(IMAGES_DIR, `${base}.webp`)).size;
    avifTotal += fs.statSync(path.join(IMAGES_DIR, `${base}.avif`)).size;
  }
  const mb = n => (n / 1024 / 1024).toFixed(2);
  console.log(`\nOriginal (JPG/PNG): ${mb(originalTotal)} MB`);
  console.log(`WebP total:          ${mb(webpTotal)} MB  (-${(100 - (webpTotal / originalTotal) * 100).toFixed(0)}%)`);
  console.log(`AVIF total:          ${mb(avifTotal)} MB  (-${(100 - (avifTotal / originalTotal) * 100).toFixed(0)}%)`);
}

run();
